service: prisma-aws-lambda-example
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-webpack-prisma

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x

functions:
  status:
    handler: handlers/status.handler
    events:
      - http:
          method: GET
          path: /
  seed:
    handler: handlers/seed.handler
    events:
      - http:
          method: GET
          path: /seed
  getUsers:
    handler: handlers/users.handler
    events:
      - http:
          method: GET
          path: /users
  createUser:
    handler: handlers/create-user.handler
    events:
      - http:
          method: POST
          path: /users
  getPosts:
    handler: handlers/posts.handler
    events:
      - http:
          method: GET
          path: /posts

# only include the Prisma binary required on AWS Lambda while packaging
# package:
#   patterns:
    # - '!node_modules/axios'
    # - '!node_modules/.prisma/client/libquery_engine-*'
    # - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    # - '!node_modules/prisma/libquery_engine-*'
    # - '!node_modules/@prisma/engines/**'

custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore